# Generated by Django 4.1.5 on 2023-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=300)),
                (
                    "creationTime",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Время создания задачи"
                    ),
                ),
                (
                    "endTime",
                    models.DateTimeField(
                        blank=True, default=None, help_text="Время завершения задачи"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, help_text="Выполнено"),
                ),
            ],
            options={
                "ordering": ["-creationTime"],
            },
        ),
    ]
