# Generated by Django 4.1.5 on 2023-02-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="endTime",
            field=models.DateTimeField(
                blank=True, default=None, help_text="Время завершения задачи", null=True
            ),
        ),
    ]
